### PR TITLE
Workspaces & repo overhaul

### PR DESCRIPTION
**Pull request by chriscn**
As explored in #11 this PR answers those proposes some new options.

### CODE REVIEW

**Comment by chriscn** [comment]
@Jbithell what is the status on this?

**Comment by Jbithell** [comment]
> @Jbithell what is the status on this?
> 

If the PR gets merged for the roadmap, we'll probably delete the API directory so this I'm afraid won't get merged.

**Comment by chriscn** [comment]
> > @Jbithell what is the status on this?
> 
> If the PR gets merged for the roadmap, we'll probably delete the API directory so this I'm afraid won't get merged.

Is the plan to just get rid of the workspaces and move everything to a top level directory then?

**Comment by Jbithell** [comment]
> > > @Jbithell what is the status on this?
> > 
> > If the PR gets merged for the roadmap, we'll probably delete the API directory so this I'm afraid won't get merged.
> 
> Is the plan to just get rid of the workspaces and move everything to a top level directory then?

Not sure, probably not? Just because moving to a top level would I think ruin the git history and then make it hard to move back to a monorepo when we push the button on API v2

**Comment by chriscn** [comment]
> > > > @Jbithell what is the status on this?
> > > 
> > > 
> > > If the PR gets merged for the roadmap, we'll probably delete the API directory so this I'm afraid won't get merged.
> > 
> > 
> > Is the plan to just get rid of the workspaces and move everything to a top level directory then?
> 
> Not sure, probably not? Just because moving to a top level would I think ruin the git history and then make it hard to move back to a monorepo when we push the button on API v2

I still think that we should remove the ignore for the root `package-lock.json`

**Comment by Jbithell** [comment]
> > > > > @Jbithell what is the status on this?
> > > > 
> > > > 
> > > > If the PR gets merged for the roadmap, we'll probably delete the API directory so this I'm afraid won't get merged.
> > > 
> > > 
> > > Is the plan to just get rid of the workspaces and move everything to a top level directory then?
> > 
> > 
> > Not sure, probably not? Just because moving to a top level would I think ruin the git history and then make it hard to move back to a monorepo when we push the button on API v2
> 
> I still think that we should remove the ignore for the root `package-lock.json`

I've removed it from `.gitignore`, pushed to `main`, and merged `main` into this branch. 

Given it's not really a monorepo anymore I think we close this and set it all up again if it becomes a repo with a 2nd project in again?

**Comment by chriscn** [comment]
Completely agree 👍 
Will close now.

**Pull request closed without merging**
